```{r}
rm(list=ls())
devtools::install_local("/Users/Jason/Developer/Research/randomer_forest/R-RerF/")
devtools::load_all("~/Developer/Research/randomer_forest/R-RerF/R/")

library(mlbench)
library(randomForest)

data("BreastCancer")
```


```{r}

X <- cbind(
  BreastCancer$Cl.thickness,
  BreastCancer$Cell.shape,
  BreastCancer$Cell.size,
  BreastCancer$Marg.adhesion,
  BreastCancer$Epith.c.size,
  BreastCancer$Bare.nuclei,
  BreastCancer$Bl.cromatin,
  BreastCancer$Normal.nucleoli,
  BreastCancer$Mitoses
)
# X[is.na(X)] <- 0
Y <- sapply(BreastCancer$Class, function(x) ifelse(x == "benign", 0L, 1L))

Y <- Y[rowSums(is.na(X)) == 0] 
X <- X[rowSums(is.na(X)) == 0,]

Y <- factor(Y)

N <- length(Y)
ordering <- sample(N,N)
split.frac <- 9/10

# Set aside training data
bc.Xtrain <- X[ordering[1:ceiling(N*split.frac)],]
bc.Ytrain <- Y[ordering[1:ceiling(N*split.frac)]]

# Set aside test data
bc.Xtest <- X[ordering[ceiling(N*split.frac):N],]
bc.Ytest <- Y[ordering[ceiling(N*split.frac):N]]
```



```{r}
# Randomer Forest
set.seed(1)
p = dim(X)[2]
d = p
# d = sqrt(dim(X)[2])
rerf.model <- RerF(bc.Xtrain,
                   bc.Ytrain, 
                   num.cores = 1L,
                   mat.options=list(p,d,'rf'))
rerf.predictions <- Predict(data.frame(bc.Xtest), rerf.model, num.cores = 1L)
print(mean(rerf.predictions != bc.Ytest))
```

# Set up RF Model
```{r}
set.seed(1)

# Formulae
# rf.model <- randomForest(bh.Ytrain ~ ., data=data.frame(cbind(bh.Xtrain, bh.Ytrain)))

# Non-Formulae
rf.model <- randomForest(x=data.frame(bc.Xtrain), 
                         y=bc.Ytrain,
                         xtest=data.frame(bc.Xtest), 
                         ytest=bc.Ytest, 
                         proximity = F,
                         keep.forest = T)
print(mean(rf.model$test$predicted != bc.Ytest))
```
