```{r}
rm(list=ls())
devtools::install_local("/Users/Jason/Developer/Research/randomer_forest/R-RerF/")
devtools::load_all("~/Developer/Research/randomer_forest/R-RerF/R/")


library(AUC)
library(dummies)
library(mlbench)
library(randomForest)
```

# Set up housing data
```{r}
data(BostonHousing)
X <- cbind(
  BostonHousing$crim,
  BostonHousing$zn,
  BostonHousing$indus,
  BostonHousing$chas,
  # BostonHousing$nox,
  BostonHousing$rm,
  BostonHousing$age,
  BostonHousing$dis,
  BostonHousing$rad,
  BostonHousing$tax,
  BostonHousing$ptratio,
  BostonHousing$b,
  BostonHousing$lstat)
Y <- BostonHousing$medv

N <- length(Y)
ordering <- sample(N,N)
split.frac <- 9/10

# Set aside training data
bh.Xtrain <- X[ordering[1:ceiling(N*split.frac)],]
bh.Ytrain <- Y[ordering[1:ceiling(N*split.frac)]]

# Set aside test data
bh.Xtest <- X[ordering[ceiling(N*split.frac):N],]
bh.Ytest <- Y[ordering[ceiling(N*split.frac):N]]
```


# Set up RerF Model
```{r}
# Randomer Forest
set.seed(1)
p = dim(X)[2]
d = sqrt(dim(X)[2])
rerf.model <- RerF(bh.Xtrain,
                   bh.Ytrain, 
                   num.cores = 1L, 
                   task="regression",
                   mat.options=list(p,d,'rf'))
```

# Set up RF Model
```{r}
set.seed(1)

# Formulae
# rf.model <- randomForest(bh.Ytrain ~ ., data=data.frame(cbind(bh.Xtrain, bh.Ytrain)))

# Non-Formulae
rf.model <- randomForest(x=data.frame(bh.Xtrain), 
                         y=bh.Ytrain, 
                         xtest=data.frame(bh.Xtest), 
                         ytest=bh.Ytest, 
                         proximity = F,
                         keep.forest = T)
```

# Print results
```{r}
# RerF
rerf.predictions <- Predict(bh.Xtest, rerf.model, num.cores = 1L, task='regression')
rerf.mse <- round(mean((rerf.predictions - bh.Ytest)^2), digits=2)
rerf.rmse <- round(sqrt(rerf.mse), digits=2)
print(paste0("RerF MSE: ",rerf.mse))
print(paste0("RerF RMSE: ",rerf.rmse))

# RF
rf.predictions <- rf.model$test$predicted
rf.mse <- round(mean((rf.predictions - bh.Ytest)^2), digits=2)
rf.rmse <- round(sqrt(rf.mse), digits=2)
print(paste0("RF MSE: ", rf.mse))
print(paste0("RF RMSE: ", rf.rmse))
```

Plotting results for RerF and RF separately
```{r}
# Results with RerF
# png('rerf_regresion_results.png', width=1080)
barplot(rbind(t(rerf.predictions),bh.Ytest), col=c('red', 'cyan'), beside = T,ylim=c(0,60), main="Regression-RerF results on Boston Housing prices", xlab = "Houses", ylab="Prices", sub=paste(paste0("MSE: ",rerf.mse),  paste0("RMSE: ",rerf.rmse)))
legend(0,60, c("Predict", "True"), cex=.8, col=c("tan2", "darkslategray3"), pch=c(22,0))

# Results with RF
# png('rf_regresion_results.png', width=1080)
barplot(rbind(t(rf.predictions),bh.Ytest), col=c('red', 'cyan'), beside = T,ylim=c(0,60), main="Regression-RF results on Boston Housing prices", xlab = "Houses", ylab="Prices", sub=paste(paste0("MSE: ",rf.mse),  paste0("RMSE: ",rf.rmse)))
legend(0,60, c("Predict", "True"), cex=.8, col=c("tan2", "darkslategray3"), pch=c(22,0))

# y_rerf - y_rf
# png('regression_difference_results.png', width=1080)
barplot(t(rf.predictions - rerf.predictions),  main="Regression-RF results on Boston Housing prices", xlab = "Houses", ylab="(y_rf) - (y_rerf)", ylim=c(-10,10))
# legend(0,60, c("Predict", "True"), cex=.8, col=c("tan2", "darkslategray3"), pch=c(22,0))

```

Plotting results for both same plot
```{r}
png('regression_results.png', width=1080)
par(mfrow=c(2,1))

barplot(rbind(t(rerf.predictions),bh.Ytest), col=c('red', 'cyan'), beside = T,ylim=c(0,60), main="RerF results on Boston Housing prices", xlab = "Houses", ylab="Prices", sub=paste(paste0("MSE: ",rerf.mse),  paste0("RMSE: ",rerf.rmse)))
legend(0,60, c("Predict", "True"), cex=.4, col=c("tan2", "darkslategray3"), pch=c(22,0))

barplot(rbind(t(rf.predictions),bh.Ytest), col=c('red', 'cyan'), beside = T,ylim=c(0,60), main="RF results on Boston Housing prices", xlab = "Houses", ylab="Prices", sub=paste(paste0("MSE: ",rf.mse),  paste0("RMSE: ",rf.rmse)))

# title("Regression comparison between RF and RerF", outer=T)
```


