---
title: "Test speed and accuracy of R-Rerf Iteration 6"
author: "James Browne"
date: "March 31, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message=FALSE, cache = FALSE)
#source('~/dropbox/gitRepos/R-RerF/rfr_function.R')
source('~/dropbox/gitRepos/R-RerF/rfr_mod.R')
library(compiler)
setCompilerOptions("optimize"=3)
rfr <- cmpfun(rfr)
error_rate <- cmpfun(error_rate)
#enableJIT(0)
```
This iteration adds additional features such as cross validation, bagging, and max depth level.
**********************************************************************
#### 10 runs iris, mtry=0, MinParent=6, trees=100, MaxDepth=0, bagging = .20
**********************************************************************
```{r run-iris, cache = FALSE}
#prepare data
X <- as.matrix(iris[,1:4])
Y <- as.numeric(iris[,5])
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
cat("|")
}
cat("iris training complete:\nTraining Time Summary\n")
summary(ptmtrain)
cat("iris error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```

**********************************************************************
#### 10 runs wdbc (569x30), mtry=0, MinParent=6, trees=100, MaxDepth=0, bagging = .20
**********************************************************************
```{r run-wdbc, cache = FALSE}
#prepare data
X <- read.csv("~/dropbox/gitRepos/R-RerF/data/wdbc.data", header=FALSE)
Y <- as.numeric(X[,2])
X <- X[,3:ncol(X)]
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
cat("|")
}
cat("wdbc training complete:\nTraining Time Summary:\n")
summary(ptmtrain)
cat("wdbc error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```

**********************************************************************
#### 10 runs Easy set (2000x2), mtry=0, MinParent=6, trees=100, MaxDepth=0, bagging = .20
**********************************************************************
```{r run-easy, cache = FALSE}
#prepare data
X <- read.csv("~/dropbox/gitRepos/R-RerF/data/easy_gen.csv", header = TRUE)
Y <- X[,3]+1 #don't forget to start at 1 instead of 0.
X<- X[,1:2]
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
cat("|")
}
cat("Easy set training complete:\nTraining Time Summary\n")
summary(ptmtrain)
cat("Easy set error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```

**********************************************************************
#### 10 runs Trunk (1000x10), mtry=0, MinParent=6, trees=100, MaxDepth=0, bagging = .20
**********************************************************************
```{r run-trunk, cache = FALSE}
#prepare data
X <- read.csv("~/dropbox/gitRepos/R-RerF/data/Trunk/Trunk_Xtrain.dat", header = FALSE)
Y <- read.csv("~/dropbox/gitRepos/R-RerF/data/Trunk/Trunk_Ytrain.dat", header = FALSE)+1
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
cat("|")
}
cat("Trunk set training complete:\nTraining Time Summary\n")
summary(ptmtrain)
cat("Trunk set error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```