---
title: "Test speed and accuracy of R-Rerf Iteration 2"
author: "James Browne"
date: "March 22, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message=FALSE, cache = FALSE)
source('~/dropbox/gitRepos/R-RerF/rfr_function.R')
```
In this iteration I have merged the build tree and forest creation functions.  This reduced the number of times memory gets allocated.
**********************************************************************************
#### 10 runs iris, trees=100, min node=6, mtry=0
**********************************************************************************
```{r run-iris, cache = FALSE}
#prepare data
X <- as.matrix(iris[,1:4])
Y <- as.numeric(iris[,5])
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
}
cat("iris training complete:\nTraining Time Summary\n")
summary(ptmtrain)
cat("iris error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```

**********************************************************************************
#### 10 runs wdbc, trees=100, min node=6, mtry=0
**********************************************************************************
```{r run-wdbc, cache = FALSE}
#prepare data
X <- read.csv("~/dropbox/gitRepos/R-RerF/data/wdbc.data", header=FALSE);
Y <- as.numeric(X[,2])
X <- X[,3:ncol(X)]
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
}
cat("wdbc training complete:\nTraining Time Summary:\n")
summary(ptmtrain)
cat("wdbc error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```

**********************************************************************************
#### 10 runs Easy set (2000x2), trees=100, min node=6, mtry=0
**********************************************************************************
```{r run-easy, cache = FALSE}
#prepare data
X <- read.csv("~/dropbox/gitRepos/R-RerF/data/easy_gen.csv", header = TRUE);
Y <- X[,3]+1; #don't forget to start at 1 instead of 0.
X<- X[,1:2];
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
}
cat("Easy set training complete:\nTraining Time Summary\n")
summary(ptmtrain)
cat("Easy set error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```

**********************************************************************************
#### 10 runs Trunk (1000x10), trees=100, min node=6, mtry=0
**********************************************************************************
```{r run-trunk, cache = FALSE}
#prepare data
X <- read.csv("~/dropbox/gitRepos/R-RerF/data/easy_gen.csv", header = TRUE);
Y <- X[,3]+1; #don't forget to start at 1 instead of 0.
X<- X[,1:2];
ptmtrain <- NA
ptmtest <- NA
error <- NA
for (i in 1:10){
ptm <- proc.time()
forest<-rfr(X,Y) 
ptmtrain[i]<- (proc.time() - ptm)[3]
ptm <- proc.time()
error[i] <- error_rate(X,Y,forest)
ptmtest[i]<- (proc.time() - ptm)[3]
}
cat("Easy set training complete:\nTraining Time Summary\n")
summary(ptmtrain)
cat("Easy set error complete:\nError Summary:\n")
summary(error)
cat("Test Time Summary:\n")
summary(ptmtest)
```