// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// packForestRCPP
void packForestRCPP();
RcppExport SEXP _rerf_packForestRCPP() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    packForestRCPP();
    return R_NilValue;
END_RCPP
}
// predictRF
Rcpp::NumericVector predictRF(const NumericMatrix mat, const int numCores);
RcppExport SEXP _rerf_predictRF(SEXP matSEXP, SEXP numCoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int >::type numCores(numCoresSEXP);
    rcpp_result_gen = Rcpp::wrap(predictRF(mat, numCores));
    return rcpp_result_gen;
END_RCPP
}
// findSplit
List findSplit(const NumericVector x, const IntegerVector y, const int& ndSize, const double& I, double maxdI, int bv, double bs, const int nzidx, arma::vec cc);
RcppExport SEXP _rerf_findSplit(SEXP xSEXP, SEXP ySEXP, SEXP ndSizeSEXP, SEXP ISEXP, SEXP maxdISEXP, SEXP bvSEXP, SEXP bsSEXP, SEXP nzidxSEXP, SEXP ccSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int& >::type ndSize(ndSizeSEXP);
    Rcpp::traits::input_parameter< const double& >::type I(ISEXP);
    Rcpp::traits::input_parameter< double >::type maxdI(maxdISEXP);
    Rcpp::traits::input_parameter< int >::type bv(bvSEXP);
    Rcpp::traits::input_parameter< double >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< const int >::type nzidx(nzidxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cc(ccSEXP);
    rcpp_result_gen = Rcpp::wrap(findSplit(x, y, ndSize, I, maxdI, bv, bs, nzidx, cc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rerf_packForestRCPP", (DL_FUNC) &_rerf_packForestRCPP, 0},
    {"_rerf_predictRF", (DL_FUNC) &_rerf_predictRF, 2},
    {"_rerf_findSplit", (DL_FUNC) &_rerf_findSplit, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_rerf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
