# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findSplit <- function(x, y, ndSize, I, maxdI, bv, bs, nzidx, cc) {
    .Call('_rerf_findSplit', PACKAGE = 'rerf', x, y, ndSize, I, maxdI, bv, bs, nzidx, cc)
}

testFun <- function() {
    .Call('_rerf_testFun', PACKAGE = 'rerf')
}

predictRF <- function(mat) {
    .Call('_rerf_predictRF', PACKAGE = 'rerf', mat)
}

